
### profile info
OPTIONS {{host}}/api/profiles/tom
Origin: http://bd.com
Access-Control-Request-Method: POST
Access-Control-Request-Headers: Authorization

### Get profile
GET {{host}}/api/profiles/tom
Authorization: {{token}}

### follow user
POST {{host}}/api/profiles/tom/follow
Content-Type: application/json
Authorization: {{token}}

### unfollow user
DELETE {{host}}/api/profiles/tom/follow
Content-Type: application/json
Authorization: {{token}}
