// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kratos-realworld/internal/data/ent/follow"
	"kratos-realworld/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FollowUpdate is the builder for updating Follow entities.
type FollowUpdate struct {
	config
	hooks    []Hook
	mutation *FollowMutation
}

// Where appends a list predicates to the FollowUpdate builder.
func (fu *FollowUpdate) Where(ps ...predicate.Follow) *FollowUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetUserID sets the "user_id" field.
func (fu *FollowUpdate) SetUserID(i int64) *FollowUpdate {
	fu.mutation.ResetUserID()
	fu.mutation.SetUserID(i)
	return fu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (fu *FollowUpdate) SetNillableUserID(i *int64) *FollowUpdate {
	if i != nil {
		fu.SetUserID(*i)
	}
	return fu
}

// AddUserID adds i to the "user_id" field.
func (fu *FollowUpdate) AddUserID(i int64) *FollowUpdate {
	fu.mutation.AddUserID(i)
	return fu
}

// SetBeUserID sets the "be_user_id" field.
func (fu *FollowUpdate) SetBeUserID(i int64) *FollowUpdate {
	fu.mutation.ResetBeUserID()
	fu.mutation.SetBeUserID(i)
	return fu
}

// SetNillableBeUserID sets the "be_user_id" field if the given value is not nil.
func (fu *FollowUpdate) SetNillableBeUserID(i *int64) *FollowUpdate {
	if i != nil {
		fu.SetBeUserID(*i)
	}
	return fu
}

// AddBeUserID adds i to the "be_user_id" field.
func (fu *FollowUpdate) AddBeUserID(i int64) *FollowUpdate {
	fu.mutation.AddBeUserID(i)
	return fu
}

// Mutation returns the FollowMutation object of the builder.
func (fu *FollowUpdate) Mutation() *FollowMutation {
	return fu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FollowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FollowUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FollowUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FollowUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FollowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeInt64))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.UserID(); ok {
		_spec.SetField(follow.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := fu.mutation.AddedUserID(); ok {
		_spec.AddField(follow.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := fu.mutation.BeUserID(); ok {
		_spec.SetField(follow.FieldBeUserID, field.TypeInt64, value)
	}
	if value, ok := fu.mutation.AddedBeUserID(); ok {
		_spec.AddField(follow.FieldBeUserID, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FollowUpdateOne is the builder for updating a single Follow entity.
type FollowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FollowMutation
}

// SetUserID sets the "user_id" field.
func (fuo *FollowUpdateOne) SetUserID(i int64) *FollowUpdateOne {
	fuo.mutation.ResetUserID()
	fuo.mutation.SetUserID(i)
	return fuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (fuo *FollowUpdateOne) SetNillableUserID(i *int64) *FollowUpdateOne {
	if i != nil {
		fuo.SetUserID(*i)
	}
	return fuo
}

// AddUserID adds i to the "user_id" field.
func (fuo *FollowUpdateOne) AddUserID(i int64) *FollowUpdateOne {
	fuo.mutation.AddUserID(i)
	return fuo
}

// SetBeUserID sets the "be_user_id" field.
func (fuo *FollowUpdateOne) SetBeUserID(i int64) *FollowUpdateOne {
	fuo.mutation.ResetBeUserID()
	fuo.mutation.SetBeUserID(i)
	return fuo
}

// SetNillableBeUserID sets the "be_user_id" field if the given value is not nil.
func (fuo *FollowUpdateOne) SetNillableBeUserID(i *int64) *FollowUpdateOne {
	if i != nil {
		fuo.SetBeUserID(*i)
	}
	return fuo
}

// AddBeUserID adds i to the "be_user_id" field.
func (fuo *FollowUpdateOne) AddBeUserID(i int64) *FollowUpdateOne {
	fuo.mutation.AddBeUserID(i)
	return fuo
}

// Mutation returns the FollowMutation object of the builder.
func (fuo *FollowUpdateOne) Mutation() *FollowMutation {
	return fuo.mutation
}

// Where appends a list predicates to the FollowUpdate builder.
func (fuo *FollowUpdateOne) Where(ps ...predicate.Follow) *FollowUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FollowUpdateOne) Select(field string, fields ...string) *FollowUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Follow entity.
func (fuo *FollowUpdateOne) Save(ctx context.Context) (*Follow, error) {
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FollowUpdateOne) SaveX(ctx context.Context) *Follow {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FollowUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FollowUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FollowUpdateOne) sqlSave(ctx context.Context) (_node *Follow, err error) {
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeInt64))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Follow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, follow.FieldID)
		for _, f := range fields {
			if !follow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != follow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.UserID(); ok {
		_spec.SetField(follow.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := fuo.mutation.AddedUserID(); ok {
		_spec.AddField(follow.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := fuo.mutation.BeUserID(); ok {
		_spec.SetField(follow.FieldBeUserID, field.TypeInt64, value)
	}
	if value, ok := fuo.mutation.AddedBeUserID(); ok {
		_spec.AddField(follow.FieldBeUserID, field.TypeInt64, value)
	}
	_node = &Follow{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
