// +build tools
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kratos-realworld/internal/data/ent/article"
	"kratos-realworld/internal/data/ent/favorite"
	"kratos-realworld/internal/data/ent/follow"
	"kratos-realworld/internal/data/ent/schema"
	"kratos-realworld/internal/data/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescSlug is the schema descriptor for slug field.
	articleDescSlug := articleFields[2].Descriptor()
	// article.DefaultSlug holds the default value on creation for the slug field.
	article.DefaultSlug = articleDescSlug.Default.(func() uuid.UUID)
	// articleDescTitle is the schema descriptor for title field.
	articleDescTitle := articleFields[3].Descriptor()
	// article.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	article.TitleValidator = articleDescTitle.Validators[0].(func(string) error)
	// articleDescDescription is the schema descriptor for description field.
	articleDescDescription := articleFields[4].Descriptor()
	// article.DefaultDescription holds the default value on creation for the description field.
	article.DefaultDescription = articleDescDescription.Default.(string)
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[7].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	// articleDescUpdatedAt is the schema descriptor for updated_at field.
	articleDescUpdatedAt := articleFields[8].Descriptor()
	// article.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	article.DefaultUpdatedAt = articleDescUpdatedAt.Default.(func() time.Time)
	// article.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	article.UpdateDefaultUpdatedAt = articleDescUpdatedAt.UpdateDefault.(func() time.Time)
	favoriteFields := schema.Favorite{}.Fields()
	_ = favoriteFields
	// favoriteDescCreatedAt is the schema descriptor for created_at field.
	favoriteDescCreatedAt := favoriteFields[2].Descriptor()
	// favorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	favorite.DefaultCreatedAt = favoriteDescCreatedAt.Default.(func() time.Time)
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescUserID is the schema descriptor for user_id field.
	followDescUserID := followFields[1].Descriptor()
	// follow.DefaultUserID holds the default value on creation for the user_id field.
	follow.DefaultUserID = followDescUserID.Default.(int64)
	// followDescBeUserID is the schema descriptor for be_user_id field.
	followDescBeUserID := followFields[2].Descriptor()
	// follow.DefaultBeUserID holds the default value on creation for the be_user_id field.
	follow.DefaultBeUserID = followDescBeUserID.Default.(int64)
	// followDescCreatedAt is the schema descriptor for created_at field.
	followDescCreatedAt := followFields[3].Descriptor()
	// follow.DefaultCreatedAt holds the default value on creation for the created_at field.
	follow.DefaultCreatedAt = followDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescBio is the schema descriptor for bio field.
	userDescBio := userFields[4].Descriptor()
	// user.DefaultBio holds the default value on creation for the bio field.
	user.DefaultBio = userDescBio.Default.(string)
	// userDescImage is the schema descriptor for image field.
	userDescImage := userFields[5].Descriptor()
	// user.DefaultImage holds the default value on creation for the image field.
	user.DefaultImage = userDescImage.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
