// Code generated by ent, DO NOT EDIT.

package follow

import (
	"kratos-realworld/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldUserID, v))
}

// BeUserID applies equality check predicate on the "be_user_id" field. It's identical to BeUserIDEQ.
func BeUserID(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldBeUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldUserID, v))
}

// BeUserIDEQ applies the EQ predicate on the "be_user_id" field.
func BeUserIDEQ(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldBeUserID, v))
}

// BeUserIDNEQ applies the NEQ predicate on the "be_user_id" field.
func BeUserIDNEQ(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldBeUserID, v))
}

// BeUserIDIn applies the In predicate on the "be_user_id" field.
func BeUserIDIn(vs ...int64) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldBeUserID, vs...))
}

// BeUserIDNotIn applies the NotIn predicate on the "be_user_id" field.
func BeUserIDNotIn(vs ...int64) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldBeUserID, vs...))
}

// BeUserIDGT applies the GT predicate on the "be_user_id" field.
func BeUserIDGT(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldBeUserID, v))
}

// BeUserIDGTE applies the GTE predicate on the "be_user_id" field.
func BeUserIDGTE(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldBeUserID, v))
}

// BeUserIDLT applies the LT predicate on the "be_user_id" field.
func BeUserIDLT(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldBeUserID, v))
}

// BeUserIDLTE applies the LTE predicate on the "be_user_id" field.
func BeUserIDLTE(v int64) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldBeUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Follow {
	return predicate.Follow(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Follow) predicate.Follow {
	return predicate.Follow(sql.NotPredicates(p))
}
